In [165]:
import numpy as np

In [37]:
np.__version__

'1.19.2'

In [38]:
# 1D array
arr = np.array([1, 2, 3, 4])

In [39]:
arr

array([1, 2, 3, 4])

In [40]:
arr.shape

(4,)

In [41]:
arr.dtype

dtype('int32')

In [42]:
arr.ndim

1

In [43]:
type(arr)  # n dimensional array

numpy.ndarray

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
# to skip number
arr = np.arange(1, 20, 4)

In [47]:
arr

array([ 1,  5,  9, 13, 17])

In [48]:
#2D array
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12] ])

In [49]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr_2d.shape

(4, 3)

In [51]:
arr_2d.ndim

2

In [52]:
np.zeros((3,3)) # empty matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
arr = np.array([1, 5, 9, 13, 17], dtype=float)

In [55]:
arr

array([ 1.,  5.,  9., 13., 17.])

In [56]:
arr = np.array([1, 5, 9, 13, 17], dtype=str)

In [57]:
arr

array(['1', '5', '9', '13', '17'], dtype='<U2')

In [58]:
#identity matrix
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.eye(5).shape

(5, 5)

In [60]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [61]:
np.full((3,3),9) #num

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [62]:
np.full((4,4), 'L') #str

array([['L', 'L', 'L', 'L'],
       ['L', 'L', 'L', 'L'],
       ['L', 'L', 'L', 'L'],
       ['L', 'L', 'L', 'L']], dtype='<U1')

In [63]:
np.full((3,3), 5.0)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [183]:
arr2= np.array([1, 2, 3, 4])

In [168]:
arr2= np.diag([1, 2, 3, 4])

In [169]:
arr3= np.eye(3, dtype=int)

In [180]:
arr3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [184]:
np.concatenate((arr2, arr3))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [185]:
 np.concatenate((arr2,arr3), axis=1) #column arrangement

AxisError: axis 1 is out of bounds for array of dimension 1

In [138]:
np.vstack((arr2,arr3)) #vertical stack

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 18 and the array at index 1 has size 6

In [ ]:
np.hstack((arr2,arr3)) #horizontal stack

In [72]:
np.random.randint(0,10,(4,4)) #random number generation

array([[5, 1, 8, 9],
       [2, 4, 9, 9],
       [5, 4, 2, 9],
       [9, 3, 1, 2]])

In [73]:
np.triu([[1,2,3], [4,5,6],[7,8,9], [1,2,3]], -1) #triangular matrix

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9],
       [0, 0, 3]])

# Array Indexing

In [74]:
arr = np.array([1, 3, 5, 7, 4, 9, 10])

In [75]:
arr

array([ 1,  3,  5,  7,  4,  9, 10])

In [76]:
arr[0]

1

In [77]:
arr[-1]

10

In [78]:
arr[-2]

9

In [140]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [175]:
arr2[1,1]

2

In [176]:
arr2[3,3]

4

In [177]:
arr2[3,-1]

4

In [178]:
arr2[1,0]= 5 # to replace the value from the matrix

In [179]:
arr2*2

array([[ 2,  0,  0,  0],
       [10,  4,  0,  0],
       [ 0,  0,  6,  0],
       [ 0,  0,  0,  8]])

# Array Slicing

In [85]:
arr

array([ 1,  3,  5,  7,  4,  9, 10])

In [86]:
#arr[start:stop:step]
arr[0:6]


array([1, 3, 5, 7, 4, 9])

In [87]:
arr[:]

array([ 1,  3,  5,  7,  4,  9, 10])

In [88]:
arr[3:]

array([ 7,  4,  9, 10])

In [89]:
arr[4:] #index position

array([ 4,  9, 10])

In [90]:
arr[2:5]

array([5, 7, 4])

In [91]:
arr[::2] #alternate numbers

array([ 1,  5,  4, 10])

In [92]:
arr[1::3]

array([3, 4])

In [95]:
arr[::-1] #reverse

array([10,  9,  4,  7,  5,  3,  1])

In [96]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
arr_2d[:2, ::2]

array([[1, 3],
       [4, 6]])

In [99]:
arr_2d[2:4,::]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [100]:
arr_2d[2:4,:4]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [101]:
arr_2d[2:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [102]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [103]:
arr_2d[:,:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [104]:
arr_2d[2:,:2]

array([[ 7,  8],
       [10, 11]])

In [105]:
arr_2d[2:, :-1]

array([[ 7,  8],
       [10, 11]])

In [106]:
arr_b = arr

In [107]:
arr_b

array([ 1,  3,  5,  7,  4,  9, 10])

In [108]:
arr_b[0]= 2

In [109]:
arr_b

array([ 2,  3,  5,  7,  4,  9, 10])

In [110]:
#for copying
arr_b = arr.copy()

In [111]:
arr_b

array([ 2,  3,  5,  7,  4,  9, 10])

In [112]:
arr_b[0]=20

In [113]:
arr_b

array([20,  3,  5,  7,  4,  9, 10])

In [114]:
arr

array([ 2,  3,  5,  7,  4,  9, 10])

In [115]:
np.shares_memory(arr, arr_b)

False

In [116]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.dot(arr1,arr2) #dot product

32

In [117]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [118]:
arr_2d.T #transpose

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [119]:
np.sum(arr1)

6

In [120]:
np.median(arr1)

2.0

In [121]:
arr1.std() # std deviation

0.816496580927726

In [122]:
x=np.array([0,1,0,1],dtype=bool)
y=np.array([0,0,1,1], dtype=bool)
# AND Gate op=(0,0,0,1)
np.logical_and(x,y)

array([False, False, False,  True])

In [123]:
#OR gate op=(0,1,1,1)
np.logical_or(x,y)

array([False,  True,  True,  True])

In [124]:
arr1

array([1, 2, 3])

In [125]:
arr1.shape #reshaping array

(3,)

In [126]:
arr1.reshape((3,1)) 

array([[1],
       [2],
       [3]])

In [127]:
arr2 = np.arange(18)

In [128]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [129]:
arr2.reshape((6,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [130]:
arr2.reshape(3,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [131]:
arr3= np.arange(6)

In [132]:
arr3

array([0, 1, 2, 3, 4, 5])

In [133]:
arr3.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [134]:
arr2.reshape(2,3,-1) # number of matrices, elements

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [147]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [148]:
arr_2d.sum()

78

In [149]:
arr_2d.sum(axis=0) # column wise sum

array([22, 26, 30])

In [150]:
arr_2d.sum(axis=1) # row wise sum

array([ 6, 15, 24, 33])

In [151]:
arr2.max()

17

In [152]:
arr_2d.max()

12

In [153]:
arr2.min()

0

In [154]:
arr_2d.min()

1

In [155]:
arr_2d.argmax()

11

In [156]:
arr2.argmax()

17

In [159]:
arr4 = np.array([3,6,7,2,19,32,22,1,0])

In [162]:
arr4

array([ 3,  6,  7,  2, 19, 32, 22,  1,  0])

In [186]:
arr4.sort()

In [187]:
arr4

array([ 0,  1,  2,  3,  6,  7, 19, 22, 32])

In [188]:
np.sort(arr4)

array([ 0,  1,  2,  3,  6,  7, 19, 22, 32])